[package]
name = "tutara-interpreter"
version = "0.0.0"
authors = ["Niels van Velzen <git@ndat.nl>", "Marnix Wieffering <git@marnixwieffering.dev>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
